### ISSUE TITLE
Define a data format for badge/ accomplishments in the game of steaks

### ISSUE THREAD

**Issue by zmanian** [cosmos/explorer#21]
We need define a json data structure that will be served from some url like github repo. S3 bucket that will allow us to populate the game of steaks scorecard with badges for validators.

**Comment by jackzampolin** [comment]
I think that in order to converge on a data structure, we need to better understand what kind of badges and awards we will be giving out in the game of stakes. Adding a couple of folks to this conversation

cc @nylira @jolesbi @chjango

**Comment by zmanian** [comment]
Out of Scope
